// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtie1AfyED0A_pKI6r8PVGlEVgvMZV-dc',
    appId: '1:224655251939:web:e476fd81401b90028228d6',
    messagingSenderId: '224655251939',
    projectId: 'padem-535a1',
    authDomain: 'padem-535a1.firebaseapp.com',
    databaseURL: 'https://padem-535a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'padem-535a1.appspot.com',
    measurementId: 'G-R8VMS8Y3XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1ab9IaggigEeJFZq6Ah58JBX0QuwJS4',
    appId: '1:224655251939:android:4376ae76bb91b2908228d6',
    messagingSenderId: '224655251939',
    projectId: 'padem-535a1',
    databaseURL: 'https://padem-535a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'padem-535a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHcX261cckgzXbQ4TANqPNcaUJCzu8TY',
    appId: '1:224655251939:ios:50c0fd1eac5e98478228d6',
    messagingSenderId: '224655251939',
    projectId: 'padem-535a1',
    databaseURL: 'https://padem-535a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'padem-535a1.appspot.com',
    iosBundleId: 'gov.padem.pademArsipDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHcX261cckgzXbQ4TANqPNcaUJCzu8TY',
    appId: '1:224655251939:ios:50c0fd1eac5e98478228d6',
    messagingSenderId: '224655251939',
    projectId: 'padem-535a1',
    databaseURL: 'https://padem-535a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'padem-535a1.appspot.com',
    iosBundleId: 'gov.padem.pademArsipDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtie1AfyED0A_pKI6r8PVGlEVgvMZV-dc',
    appId: '1:224655251939:web:38a40c5bc74e48d08228d6',
    messagingSenderId: '224655251939',
    projectId: 'padem-535a1',
    authDomain: 'padem-535a1.firebaseapp.com',
    databaseURL: 'https://padem-535a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'padem-535a1.appspot.com',
    measurementId: 'G-6ZQSF6DHCV',
  );
}
